[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
common = "HokPKpkSoJtDko4EaeKioyddtnZvedzaMDjQxzXEQ82b"
create-room-system = "CJ2ddnADWJuBeJ5vr5kCPjMiZfPMT6e83bU4kBAsbCXz"
finalize-game-system = "5j31pAW4KRxYdWM718y2vRiL2963YE9Q3EFLZNdv3DPX"
join-room-system = "8f6SZ35jjJqHGpkrwZubfLsRaCnNRd7TKX4qRGSy1KpZ"
player = "AEg8kcweaPo1H8o98zsBuh9VfdJTj9suNdTWDzNJfBu3"
room = "4E1EMr7Df7mfNkRHnnQQDfdckcMZnq2qDKTrQUKc4wdU"
start-game-system = "GPE1cWhMgMDiVsAX8waKaqLoBq4NGD6yxLetoz3KpiHZ"
update-player-system = "Gm4mG6xn43RDxsXUjJDiUrq8vE2FWQFWj8Ez3xViPYqk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
